newProject/auth_app/urls.py
from django.urls import path
from . import views

app_name = "auth_app"

urlpatterns = [
    path('', views.index, name='auth_index'),  # empty path represents root of this app
    path('registration/', views.registration, name="registration"),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('loggedinuser/', views.loggedinuser, name='loggedinuser')
]

newProject/forms/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.form_name),  # empty path represents root of this app
]

newProject/new_app/urls.py
from django.urls import path
from . import views

app_name = "new_app"

urlpatterns = [
    path('', views.base, name='base'),  # empty path represents root of this app

]

newProject/new_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    # re_path(r'^$', base, name='base'),
    path('', include('new_app.urls')),
    path('admin/', admin.site.urls),
    path('new_app/', include('new_app.urls')),
    path('users/', include('users.urls')),
    path('forms/', include('forms.urls')),
    path('templates/', include('templates_app.urls')),
    path('auth/', include('auth_app.urls'))
]

newProject/templates_app/urls.py
from django.urls import path
from . import views

# template tagging
app_name = "templates_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('relative', views.relative, name='relative'),
    path('other', views.other, name='other'),

]

newProject/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Project</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/new_style.css' %}">
<!--    <link rel="stylesheet" href="C:\Users\shola\PycharmProjects\websiteCourse\newProject\static\css">-->
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'new_app:base' %}">My Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'new_app:base' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'templates_app:index' %}">Templates</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'templates_app:other' %}">Other</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'auth_app:auth_index' %}">User Auth</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

    </ul>
    <ul class="navbar-nav ms-auto">
      <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle hidden-arrow"
          href="#"
          id="navbarDropdownMenuLink"
          role="button"
          data-mdb-toggle="dropdown"
          aria-expanded="false"
        >
          <i class="fas fa-bell"></i>
          <span class="badge rounded-pill badge-notification bg-danger">1</span>
        </a>
        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuLink"
        >
          <li>
            <a class="dropdown-item" href="#">Some news</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Another news</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Something else here</a>
          </li>
        </ul>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'auth_app:user_logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'auth_app:user_login' %}">Login</a>
      </li>
      {% endif %}

    </ul>
 </div>
</nav>

<div class="container">
    <h1>Welcome Shola</h1>
    <img src="{% static 'images/django.jpg' %}" class="img-thumbnail col-lg-10 col-xs-10 center" alt="My image">
    {% block content %}
    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>