newProject/auth_app/urls.py
from django.urls import path
from . import views

app_name = "auth_app"

urlpatterns = [
    path('', views.index, name='auth_index'),  # empty path represents root of this app
    path('registration/', views.registration, name="registration"),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('loggedinuser/', views.loggedinuser, name='loggedinuser')
]

newProject/forms/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.form_name),  # empty path represents root of this app
]

newProject/new_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    # re_path(r'^$', base, name='base'),
    path('', include('new_app.urls')),
    path('admin/', admin.site.urls),
    path('new_app/', include('new_app.urls')),
    path('users/', include('users.urls')),
    path('forms/', include('forms.urls')),
    path('templates/', include('templates_app.urls')),
    path('auth/', include('auth_app.urls'))
]

newProject/auth_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional
    portfolio = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

newProject/auth_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio', 'profile_pic')

newProject/auth_app/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout


def index(request):
    return render(request, 'auth_index.html')


@login_required()
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('auth_app:user_login'))


@login_required()
def loggedinuser(request):
    return render(request, 'loggedin_page.html')


def registration(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'registration.html', {'user_form': user_form,
                                                 'profile_form': profile_form,
                                                 'registered': registered

                                                 })


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse_lazy('auth_app:loggedinuser'))
            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login and failed")
            print(f'Username: {username} and password {password}')
            return HttpResponse("Invalid login details")
    else:
        return render(request,'user_login.html')

newProject/auth_app/templates/auth_index.html
{% extends 'base.html' %}

{% block content %}

<h1>Welcome to User Auth page</h1>

<a href="{% url 'auth_app:registration' %}">Click me for the registration page</a><br>
<a href="{% url 'auth_app:user_login' %}">Click me for the login page</a><br>

{% endblock %}

newProject/auth_app/templates/loggedin_page.html
{% extends 'base.html' %}

{% block content %}



<div class="jumbotron">
  <h1>Congrats you are logged in!</h1>
</div>


{% endblock %}

newProject/auth_app/templates/registration.html
{% extends 'base.html' %}

{% block content %}

<h1>Welcome to registration page</h1>

<div class="jumbotron">
    {% if registered %}
    <h2>Thank you for registering</h2>

    {% else %}
        <h2>Fill out the form: </h2>
        <form  enctype="multipart/form-data" align="center" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>
    {% endif %}
</div>

{% endblock %}

newProject/auth_app/templates/user_login.html
{% extends 'base.html' %}

{% block content %}

<h1>Welcome to the login page</h1>



<div class="jumbotron">
    <form action="{% url 'auth_app:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password" >Password:</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">
    </form>

    <a href="{% url 'auth_app:registration' %}">Register Here</a><br>
</div>


{% endblock %}